import os
import shutil
import subprocess
import zipfile
import re

class ProjectDirService:
    BASE_DIR = os.environ.get("IDEAFORGE_PROJECTS_DIR", os.path.expanduser("~/ideaforge-projects"))
    
    @classmethod
    def create_project_dir(cls, project_id: str, project_name: str) -> str:
        """
        Create isolated project directory:
        1. Sanitize project name (lowercase, replace spaces with hyphens, remove special chars)
        2. Create directory: {BASE_DIR}/{sanitized_name}_{short_id}/
        3. Initialize git: git init
        4. Create .gitignore with common Python/Node entries
        5. Create README.md with project name
        6. Return absolute path
        
        If directory already exists, return existing path (idempotent).
        """
        os.makedirs(cls.BASE_DIR, exist_ok=True)
        sanitized = cls.sanitize_name(project_name)
        dir_name = f"{sanitized}_{project_id}"
        path = os.path.abspath(os.path.join(cls.BASE_DIR, dir_name))
        
        if os.path.exists(path):
            return path
            
        os.makedirs(path, exist_ok=True)
        
        # Initialize git
        try:
            subprocess.run(["git", "init"], cwd=path, capture_output=True)
        except Exception:
            pass
            
        # Create gitignore
        gitignore_content = """# Python
__pycache__/
*.pyc
.venv/
venv/
.pytest_cache/

# Node
node_modules/
dist/
.env
"""
        with open(os.path.join(path, ".gitignore"), "w", encoding="utf-8") as f:
            f.write(gitignore_content)
            
        # Create README.md
        readme_content = f"# {project_name}\n\nGenerated by IdeaForge.\n"
        with open(os.path.join(path, "README.md"), "w", encoding="utf-8") as f:
            f.write(readme_content)
            
        return path
    
    @classmethod
    def get_project_dir(cls, project_id: str, project_name: str) -> str:
        """Get project directory path (create if doesn't exist)"""
        return cls.create_project_dir(project_id, project_name)
    
    @classmethod
    def delete_project_dir(cls, project_dir: str) -> bool:
        """Delete project directory (used for cleanup/cancellation)"""
        try:
            if os.path.exists(project_dir):
                shutil.rmtree(project_dir)
                return True
        except Exception:
            pass
        return False
    
    @classmethod
    def get_project_structure(cls, project_dir: str, max_depth: int = 3) -> dict:
        """
        Return directory tree as nested dict:
        {
            "name": "my-project",
            "type": "directory",
            "children": [
                {"name": "backend", "type": "directory", "children": [...]},
                {"name": "README.md", "type": "file", "size": 245}
            ]
        }
        Respects .gitignore patterns. Max depth to avoid huge trees.
        """
        def walk(current_dir, depth):
            if depth > max_depth:
                return []
                
            children = []
            try:
                for entry in os.scandir(current_dir):
                    if entry.name in {".git", "node_modules", "__pycache__", ".venv", "venv", ".pytest_cache"}:
                        continue
                    if entry.is_dir():
                        children.append({
                            "name": entry.name,
                            "type": "directory",
                            "children": walk(entry.path, depth + 1)
                        })
                    else:
                        try:
                            size = entry.stat().st_size
                        except Exception:
                            size = 0
                        children.append({
                            "name": entry.name,
                            "type": "file",
                            "size": size
                        })
            except Exception:
                pass
            children.sort(key=lambda x: (x["type"] != "directory", x["name"]))
            return children

        return {
            "name": os.path.basename(project_dir),
            "type": "directory",
            "children": walk(project_dir, 1)
        }
    
    @classmethod
    def get_file_content(cls, project_dir: str, file_path: str) -> str | None:
        """
        Read a file from the project directory.
        Security: validate file_path is within project_dir (prevent path traversal).
        Returns file content or None if not found.
        """
        try:
            abs_project_dir = os.path.abspath(project_dir)
            abs_file_path = os.path.abspath(os.path.join(project_dir, file_path))
            if not abs_file_path.startswith(abs_project_dir):
                return None
            if not os.path.isfile(abs_file_path):
                return None
            with open(abs_file_path, "r", encoding="utf-8", errors="ignore") as f:
                return f.read()
        except Exception:
            return None
    
    @classmethod
    def create_zip(cls, project_dir: str) -> str:
        """
        Create a zip archive of the project directory.
        Respects .gitignore (exclude node_modules, __pycache__, .venv, etc.)
        Returns path to the zip file.
        """
        abs_project_dir = os.path.abspath(project_dir)
        parent_dir = os.path.dirname(abs_project_dir)
        project_name = os.path.basename(abs_project_dir)
        zip_path = os.path.join(parent_dir, f"{project_name}.zip")
        
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, dirs, files in os.walk(abs_project_dir):
                dirs[:] = [d for d in dirs if d not in {".git", "node_modules", "__pycache__", ".venv", "venv", ".pytest_cache"}]
                for file in files:
                    file_path = os.path.join(root, file)
                    arcname = os.path.relpath(file_path, abs_project_dir)
                    zipf.write(file_path, arcname)
        return zip_path
    
    @staticmethod
    def sanitize_name(name: str) -> str:
        """Convert project name to filesystem-safe directory name"""
        name = name.lower().strip()
        name = re.sub(r'[^a-z0-9\s-]', '', name)
        name = re.sub(r'[\s]+', '-', name)
        return name[:50]
