"""add_session_guidance

Revision ID: 787d21d232dd
Revises: c551ab5d24c6
Create Date: 2026-05-29 11:22:08.875696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787d21d232dd'
down_revision: Union[str, Sequence[str], None] = 'c551ab5d24c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('guidance', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'guidance')
    # ### end Alembic commands ###
