"""add_maturity_level_to_sessions

Revision ID: a90ce2f66ded
Revises: 09cfd74c3aa2
Create Date: 2026-05-26 11:33:49.562057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90ce2f66ded'
down_revision: Union[str, Sequence[str], None] = '09cfd74c3aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('maturity_level', sa.String(length=50), nullable=False))
    op.add_column('sessions', sa.Column('tech_stack_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'tech_stack_preferences')
    op.drop_column('sessions', 'maturity_level')
    # ### end Alembic commands ###
